version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "npx prisma migrate deploy && npm run start:prod" ]

volumes:
  mysql_data:
